---

project_name: prettypar

before:
  hooks:
    - go mod tidy -go=1.17
    - go generate ./...

builds:
  - binary: '{{ .ProjectName }}'
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - openbsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -mod=readonly
    ldflags: -s -w -X main.version={{ .Version }}
    ignore:
      - goos: darwin
        goarch: 386
      - goos: freebsd
        goarch: arm64
      - goos: netbsd
        goarch: arm64
      - goos: openbsd
        goarch: arm64

archives:
  - name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

gomod:
  proxy: true

snapshot:
  name_template: '{{ .Version }}'

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

source:
  enabled: true
  name_template: '{{ .ProjectName }}-sources'
